//! Token usage data structures

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use strum::{Display, EnumString};

/// Token usage record for a single LLM call
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenUsageRecord {
    /// Unique record ID (auto-generated by SQLite)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Timestamp of the LLM call
    pub timestamp: DateTime<Utc>,
    /// Session identifier (e.g., "telegram:user-123", "gui:chat-main")
    pub session_id: String,
    /// Endpoint/provider name (e.g., "openrouter", "deepseek")
    pub endpoint_name: String,
    /// Model identifier (e.g., "claude-3-5-sonnet", "gpt-4o")
    pub model: String,
    /// Operation type (chat, tool_call, memory_consolidation, etc.)
    pub operation_type: OperationType,
    /// Additional operation details (e.g., tool name for tool calls)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_detail: Option<String>,
    /// Input tokens (prompt + context)
    pub input_tokens: i64,
    /// Output tokens (generated content)
    pub output_tokens: i64,
    /// Cache creation tokens (for Claude prompt caching)
    #[serde(default)]
    pub cache_creation_tokens: i64,
    /// Cache read tokens (for Claude prompt caching)
    #[serde(default)]
    pub cache_read_tokens: i64,
    /// Context size at the time of call
    #[serde(default)]
    pub context_tokens: i64,
    /// Iteration number in multi-turn conversation
    #[serde(default)]
    pub iteration: u32,
    /// Channel identifier (e.g., "telegram", "discord", "gui")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    /// User identifier
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Agent profile identifier (for multi-agent scenarios)
    #[serde(default = "default_agent_profile")]
    pub agent_profile_id: String,
    /// Estimated cost in USD
    #[serde(default)]
    pub estimated_cost: f64,
}

fn default_agent_profile() -> String {
    "default".to_string()
}

impl TokenUsageRecord {
    /// Create a new token usage record
    pub fn new(
        session_id: impl Into<String>,
        endpoint_name: impl Into<String>,
        model: impl Into<String>,
        operation_type: OperationType,
        input_tokens: i64,
        output_tokens: i64,
    ) -> Self {
        Self {
            id: None,
            timestamp: Utc::now(),
            session_id: session_id.into(),
            endpoint_name: endpoint_name.into(),
            model: model.into(),
            operation_type,
            operation_detail: None,
            input_tokens,
            output_tokens,
            cache_creation_tokens: 0,
            cache_read_tokens: 0,
            context_tokens: 0,
            iteration: 0,
            channel: None,
            user_id: None,
            agent_profile_id: "default".to_string(),
            estimated_cost: 0.0,
        }
    }

    /// Add cache token information
    pub fn with_cache(mut self, creation: i64, read: i64) -> Self {
        self.cache_creation_tokens = creation;
        self.cache_read_tokens = read;
        self
    }

    /// Add context size information
    pub fn with_context(mut self, context_tokens: i64) -> Self {
        self.context_tokens = context_tokens;
        self
    }

    /// Add channel information
    pub fn with_channel(mut self, channel: impl Into<String>) -> Self {
        self.channel = Some(channel.into());
        self
    }

    /// Add user information
    pub fn with_user(mut self, user_id: impl Into<String>) -> Self {
        self.user_id = Some(user_id.into());
        self
    }

    /// Add iteration number
    pub fn with_iteration(mut self, iteration: u32) -> Self {
        self.iteration = iteration;
        self
    }

    /// Add operation detail
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.operation_detail = Some(detail.into());
        self
    }

    /// Set estimated cost
    pub fn with_cost(mut self, cost: f64) -> Self {
        self.estimated_cost = cost;
        self
    }

    /// Total tokens (input + output)
    pub fn total_tokens(&self) -> i64 {
        self.input_tokens + self.output_tokens
    }
}

/// Operation type enumeration
#[derive(Debug, Clone, Default, Serialize, Deserialize, Display, EnumString, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum OperationType {
    /// Regular chat conversation
    Chat,
    /// Tool call execution
    ToolCall,
    /// Memory consolidation operation
    MemoryConsolidation,
    /// Cron-triggered task
    CronTrigger,
    /// Subagent delegation
    Subagent,
    /// Unknown/unclassified operation
    #[default]
    Unknown,
}

/// Aggregated usage summary by a grouping dimension
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UsageSummary {
    /// Group key (e.g., endpoint name, model, session_id)
    pub group_key: String,
    /// Total input tokens
    pub total_input: i64,
    /// Total output tokens
    pub total_output: i64,
    /// Total tokens
    pub total_tokens: i64,
    /// Total cache creation tokens
    pub total_cache_creation: i64,
    /// Total cache read tokens
    pub total_cache_read: i64,
    /// Number of requests
    pub request_count: u64,
    /// Total estimated cost
    pub total_cost: f64,
}

/// Total usage statistics
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UsageTotal {
    /// Total input tokens
    pub total_input: i64,
    /// Total output tokens
    pub total_output: i64,
    /// Total tokens
    pub total_tokens: i64,
    /// Total cache creation tokens
    pub total_cache_creation: i64,
    /// Total cache read tokens
    pub total_cache_read: i64,
    /// Number of requests
    pub request_count: u64,
    /// Total estimated cost
    pub total_cost: f64,
}

/// Timeline data point for charting
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimelinePoint {
    /// Time bucket (hour or day)
    pub time_bucket: String,
    /// Total input tokens in this bucket
    pub total_input: i64,
    /// Total output tokens in this bucket
    pub total_output: i64,
    /// Total tokens in this bucket
    pub total_tokens: i64,
    /// Number of requests in this bucket
    pub request_count: u64,
}

/// Session usage detail
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionUsage {
    /// Session key
    pub session_id: String,
    /// Total input tokens
    pub total_input: i64,
    /// Total output tokens
    pub total_output: i64,
    /// Total tokens
    pub total_tokens: i64,
    /// Number of requests
    pub request_count: u64,
    /// Total estimated cost
    pub total_cost: f64,
    /// Primary model used
    pub primary_model: String,
    /// Channel identifier
    pub channel: Option<String>,
    /// Last activity timestamp
    pub last_activity: DateTime<Utc>,
}

/// Model pricing configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelPricing {
    /// Cost per 1k input tokens in USD
    pub input_per_1k: f64,
    /// Cost per 1k output tokens in USD
    pub output_per_1k: f64,
    /// Cost per 1k cache creation tokens (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_creation_per_1k: Option<f64>,
    /// Cost per 1k cache read tokens (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_read_per_1k: Option<f64>,
}

impl ModelPricing {
    /// Default pricing for unknown models
    pub fn default_pricing() -> Self {
        Self {
            input_per_1k: 0.01,
            output_per_1k: 0.03,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        }
    }

    /// Calculate cost for given token counts
    pub fn calculate_cost(
        &self,
        input_tokens: i64,
        output_tokens: i64,
        cache_creation: i64,
        cache_read: i64,
    ) -> f64 {
        let input_cost = (input_tokens as f64 / 1000.0) * self.input_per_1k;
        let output_cost = (output_tokens as f64 / 1000.0) * self.output_per_1k;

        let cache_cost = self
            .cache_creation_per_1k
            .map_or(0.0, |p| (cache_creation as f64 / 1000.0) * p)
            + self
                .cache_read_per_1k
                .map_or(0.0, |p| (cache_read as f64 / 1000.0) * p);

        input_cost + output_cost + cache_cost
    }
}

/// Well-known model pricing (approximate values as of 2024)
pub fn get_model_pricing(model: &str) -> ModelPricing {
    // Normalize model name
    let model_lower = model.to_lowercase();

    // Claude models
    if model_lower.contains("claude-3-5-sonnet") || model_lower.contains("claude-3.5-sonnet") {
        return ModelPricing {
            input_per_1k: 0.003,
            output_per_1k: 0.015,
            cache_creation_per_1k: Some(0.00375),
            cache_read_per_1k: Some(0.0003),
        };
    }
    if model_lower.contains("claude-3-opus") {
        return ModelPricing {
            input_per_1k: 0.015,
            output_per_1k: 0.075,
            cache_creation_per_1k: Some(0.01875),
            cache_read_per_1k: Some(0.0015),
        };
    }
    if model_lower.contains("claude-3-haiku") || model_lower.contains("claude-3.5-haiku") {
        return ModelPricing {
            input_per_1k: 0.00025,
            output_per_1k: 0.00125,
            cache_creation_per_1k: Some(0.0003),
            cache_read_per_1k: Some(0.00003),
        };
    }

    // GPT models
    if model_lower.contains("gpt-4o") {
        return ModelPricing {
            input_per_1k: 0.005,
            output_per_1k: 0.015,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }
    if model_lower.contains("gpt-4-turbo") || model_lower.contains("gpt-4-0125") {
        return ModelPricing {
            input_per_1k: 0.01,
            output_per_1k: 0.03,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }
    if model_lower.contains("gpt-3.5-turbo") || model_lower.contains("gpt-35-turbo") {
        return ModelPricing {
            input_per_1k: 0.0005,
            output_per_1k: 0.0015,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }

    // DeepSeek models
    if model_lower.contains("deepseek-chat") {
        return ModelPricing {
            input_per_1k: 0.00014,
            output_per_1k: 0.00028,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }
    if model_lower.contains("deepseek-reasoner") || model_lower.contains("deepseek-r1") {
        return ModelPricing {
            input_per_1k: 0.00055,
            output_per_1k: 0.00219,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }

    // Gemini models
    if model_lower.contains("gemini-1.5-pro") {
        return ModelPricing {
            input_per_1k: 0.00125,
            output_per_1k: 0.005,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }
    if model_lower.contains("gemini-1.5-flash") {
        return ModelPricing {
            input_per_1k: 0.000075,
            output_per_1k: 0.0003,
            cache_creation_per_1k: None,
            cache_read_per_1k: None,
        };
    }

    // Default pricing for unknown models
    ModelPricing::default_pricing()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_token_usage_record_creation() {
        let record = TokenUsageRecord::new(
            "test:session-1",
            "openrouter",
            "claude-3-5-sonnet",
            OperationType::Chat,
            1000,
            500,
        );
        assert_eq!(record.session_id, "test:session-1");
        assert_eq!(record.total_tokens(), 1500);
    }

    #[test]
    fn test_model_pricing_calculation() {
        let pricing = get_model_pricing("claude-3-5-sonnet-20241022");
        let cost = pricing.calculate_cost(1000, 500, 0, 0);
        // 1000 * 0.003 / 1000 + 500 * 0.015 / 1000 = 0.003 + 0.0075 = 0.0105
        assert!((cost - 0.0105).abs() < 0.0001);
    }

    #[test]
    fn test_cache_token_cost() {
        let pricing = get_model_pricing("claude-3-5-sonnet");
        let cost = pricing.calculate_cost(1000, 500, 200, 100);
        // Input: 0.003, Output: 0.0075, Cache creation: 0.00075, Cache read: 0.00003
        // Total: 0.01128
        assert!((cost - 0.01128).abs() < 0.0001);
    }
}
