export type CapabilityClass = 'MANAGER' | 'LOCAL' | 'DEFERRED' | 'REMOVED'

export interface GuiCapability {
  id: string
  entrypoint: string
  transport: 'tauri-manager-proxy' | 'tauri-local' | 'none'
  classification: CapabilityClass
  authority: string
  risk: 'read' | 'write' | 'execute' | 'lifecycle'
  failure: string
  verification: string
}

/**
 * G0 ledger for the GUI's capability domains.
 *
 * This is descriptive evidence, not a runtime allowlist. Security and domain
 * authority remain in Manager/Core; LOCAL entries are limited to desktop-host
 * concerns.
 */
export const GUI_CAPABILITIES: readonly GuiCapability[] = [
  {
    id: 'chat.turn',
    entrypoint: 'send_message / start_background_stream / stop_generation',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'AgentLoop through Manager',
    risk: 'execute',
    failure: 'Surface Manager/SSE failure; never synthesize a completed turn.',
    verification: 'ChatView.test.ts and Manager chat SSE characterization',
  },
  {
    id: 'session.lifecycle',
    entrypoint: 'get_sessions / get_session_history / reset_session / delete_session',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager session store',
    risk: 'write',
    failure: 'Keep the last projection and expose refresh/error state.',
    verification: 'ConversationSidebar.test.ts and GUI session smoke',
  },
  {
    id: 'plan.lifecycle',
    entrypoint: 'get_active_plan / approve_active_plan_execution / return_active_plan_to_draft',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager PlanStore',
    risk: 'execute',
    failure: 'Fail closed and reconcile the authoritative revision.',
    verification: 'PlanApprovalCard.test.ts and planning contract tests',
  },
  {
    id: 'command.approval',
    entrypoint: 'get_command_approvals / resolve_command_approval',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager command approval coordinator',
    risk: 'execute',
    failure: 'Preserve typed 404/409/422 semantics and reconcile pending state.',
    verification: 'ApprovalCenterCard.test.ts and command approval contract tests',
  },
  {
    id: 'command.rules',
    entrypoint: 'get_command_rules / set_command_rule_enabled / delete_command_rule',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Sandbox command rule store',
    risk: 'write',
    failure: 'Reject stale revisions; do not mutate optimistic state as fact.',
    verification: 'SandboxSettingsSection.test.ts',
  },
  {
    id: 'config.runtime',
    entrypoint: 'get_config / update_config / get_tools_config / update_tools_config',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager runtime configuration',
    risk: 'write',
    failure: 'Expose validation or availability failure.',
    verification: 'ProvidersSettings.test.ts and settings smoke',
  },
  {
    id: 'providers',
    entrypoint: 'get_providers / create_custom_provider / test_provider_model',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager provider catalog',
    risk: 'write',
    failure: 'Preserve provider error and never report a false successful test.',
    verification: 'ProvidersSettings.test.ts',
  },
  {
    id: 'skills.files',
    entrypoint: 'get_skills / upload_skill / delete_skill / upload_file',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager skill and file services',
    risk: 'write',
    failure: 'Expose upload/delete failure and retain server projection.',
    verification: 'Manager skills route tests and GUI settings smoke',
  },
  {
    id: 'mcp.servers',
    entrypoint: 'get_mcps / create_mcp / update_mcp / delete_mcp / refresh_mcp_status',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager MCP registry',
    risk: 'execute',
    failure: 'Expose connection failure; never infer connected state locally.',
    verification: 'Manager MCP route tests and GUI settings smoke',
  },
  {
    id: 'cron.jobs',
    entrypoint: 'get_cron_jobs / create_cron_job / run_cron_job / stop_cron_job_run',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager cron service',
    risk: 'execute',
    failure: 'Expose scheduler failure and refresh server state.',
    verification: 'Manager cron tests and GUI cron smoke',
  },
  {
    id: 'memory.laputa',
    entrypoint: 'laputa_* commands',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Laputa proposal and section services',
    risk: 'write',
    failure: 'Preserve typed conflict/schema errors; never apply locally.',
    verification: 'desktop.laputa.test.ts and Manager Laputa tests',
  },
  {
    id: 'autodream',
    entrypoint: 'trigger_autodream / get_autodream_run_status / cancel_autodream_run',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager AutoDream runtime',
    risk: 'execute',
    failure: 'Expose unavailable/cancel failure and refresh run state.',
    verification: 'EvolutionView.test.ts and Manager AutoDream tests',
  },
  {
    id: 'todo.execution',
    entrypoint: 'get_execution_todos / update_execution_todo',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager execution Todo projection',
    risk: 'write',
    failure: 'Preserve missing/conflict semantics.',
    verification: 'TodoCard.checklist.test.ts and Manager Todo tests',
  },
  {
    id: 'audit.logs',
    entrypoint: 'get_audit_events',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager audit store',
    risk: 'read',
    failure: 'Show query error; do not substitute an empty successful result.',
    verification: 'AuditPage.test.ts',
  },
  {
    id: 'token.statistics',
    entrypoint: 'get_token_usage_*',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager token ledger',
    risk: 'read',
    failure: 'Expose query failure and retain last known data.',
    verification: 'tokenStats.test.ts',
  },
  {
    id: 'mask.lifecycle',
    entrypoint: 'list_masks / get_active_mask / switch_mask / create_or_update_mask / delete_mask',
    transport: 'tauri-manager-proxy',
    classification: 'MANAGER',
    authority: 'Manager mask service',
    risk: 'write',
    failure: 'Expose validation failure and reconcile active mask.',
    verification: 'MaskCard.test.ts and MaskSelectorButton.test.ts',
  },
  {
    id: 'gateway.process',
    entrypoint: 'get_gateway_process_status / start_gateway / stop_gateway',
    transport: 'tauri-local',
    classification: 'LOCAL',
    authority: 'Tauri embedded gateway lifecycle',
    risk: 'lifecycle',
    failure: 'Return explicit lifecycle error; shutdown remains bounded.',
    verification: 'gateway_process_management_bugfix.rs and startup smoke',
  },
  {
    id: 'desktop.service',
    entrypoint: 'get_service_status / install_service / start_service / stop_service',
    transport: 'tauri-local',
    classification: 'LOCAL',
    authority: 'Tauri host service controller',
    risk: 'lifecycle',
    failure: 'Return operating-system error without changing domain state.',
    verification: 'Tauri service command tests and Windows smoke',
  },
  {
    id: 'desktop.preferences',
    entrypoint: 'get_gui_prefs / set_gui_prefs',
    transport: 'tauri-local',
    classification: 'LOCAL',
    authority: 'Tauri GUI preference store',
    risk: 'write',
    failure: 'Keep current preferences and surface persistence error.',
    verification: 'GUI close/tray lifecycle tests',
  },
  {
    id: 'desktop.logs',
    entrypoint: 'append_gui_log / get_gui_log_lines / get_gateway_log_lines',
    transport: 'tauri-local',
    classification: 'LOCAL',
    authority: 'Tauri local log files',
    risk: 'write',
    failure: 'Report I/O failure without fabricating records.',
    verification: 'AuditPage.test.ts and Tauri log tests',
  },
  {
    id: 'desktop.pet',
    entrypoint: 'pet_* / open_desktop_pet / close_desktop_pet',
    transport: 'tauri-local',
    classification: 'LOCAL',
    authority: 'Tauri desktop pet host',
    risk: 'lifecycle',
    failure: 'Surface host/media failure without mutating Manager state.',
    verification: 'DivaPetView.test.ts and desktop pet smoke',
  },
  {
    id: 'manager.direct-browser-http',
    entrypoint: 'none',
    transport: 'none',
    classification: 'DEFERRED',
    authority: 'No authority assigned in G0',
    risk: 'execute',
    failure: 'Unavailable; GUI continues through the Tauri Manager proxy.',
    verification: 'Capability ledger test asserts fail-closed classification',
  },
  {
    id: 'plan.history.overlay',
    entrypoint: 'none',
    transport: 'none',
    classification: 'REMOVED',
    authority: 'Removed from the product surface',
    risk: 'read',
    failure: 'No entrypoint; callers must not restore the obsolete overlay.',
    verification: 'Capability ledger test and ChatView surface tests',
  },
] as const
