// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProbeService is a bound Wails service proving the W3-2/W3-3 contract
 * surfaces on the pinned beta.27 API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CallerIsMain is the W3-3 capability gate shape: bound methods compare the
 * injected window identity against the recorded main window.
 * @param {number} mainID
 * @returns {$CancellablePromise<boolean>}
 */
export function CallerIsMain(mainID) {
    return $Call.ByID(4200463397, mainID);
}

/**
 * Identify returns the natively injected calling-window identity.
 * beta.27 puts the real webview Window into the binding-call context under
 * application.WindowKey; the header behind it is overwritten by
 * webViewAssetRequest.Header() so a forged x-wails-window-id cannot win.
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function Identify() {
    return $Call.ByID(808525659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
