export type {
  AvatarAnimationState,
  AvatarCharacterSpec,
  AvatarCommandName,
  AvatarCommandPayload,
  AvatarEventHandler,
  AvatarEventName,
  AvatarEventPayload,
  AvatarInitOptions,
  AvatarMotionEntry,
  AvatarMotionEventPayload,
  AvatarMotionKind,
  AvatarMotionState,
  AvatarMotionStatePatch,
  AvatarMood,
  AvatarRuntime,
  AvatarRuntimeCommandHandlers,
  AvatarRuntimeMetrics,
  AvatarRuntimeErrorPayload,
  AvatarRuntimeHostBridge,
  AvatarSpeechState,
  AvatarTransform,
  AvatarViewportSize,
  ChunkEventPayload,
  ChunkPlayPayload,
  HoverAutoHideState,
  PointerLockState,
  PttAudioReadyPayload,
  PttState,
  PttTranscriptionPayload,
  SubtitlePayload,
  VmcFramePayload,
} from '@morediva/shared-avatar-protocol'

export {
  AVATAR_COMMAND_NAMES,
  AVATAR_EVENT_NAMES,
} from '@morediva/shared-avatar-protocol'
